version: "3"
services:
  app:
    build:
      context: app
      target: builder
    stop_signal: SIGINT
    ports:
      - '5000'
    volumes:
      - ./app/models:/app/models
      - ./app/database:/app/database
    scale: 1
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"